version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tow_simulator
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: